apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}-deployment
  labels:
    app: {{APP_NAME}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{APP_NAME}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      containers:
        - name: {{APP_NAME}}-container
          image: ${{secrets.DOCKER_USERNAME}}/{{APP_NAME}}:{{IMAGE_TAG}}
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            # Add environment variables here if needed
            - name: ENV
              value: "production"
