apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}-service
  labels:
    app: {{APP_NAME}}
spec:
  selector:
    app: {{APP_NAME}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
