name: Connect to Azure AKS with Username and Password

on:
  workflow_run:
    workflows: ["Build & Deploy"]
    types:
      - completed
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  connect-to-aks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to Azure with Username and Password
      run: |
        az login --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}
    - name: Set up Azure CLI
      run: az account show

    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_CLUSTER_NAME }}

    - name: Verify Connection to AKS
      run: |
        kubectl get nodes
        kubectl get deployments --all-namespaces=true

    - name: Set APP_NAME from repo name
      run: |
        FULL_NAME=$(basename "${GITHUB_REPOSITORY}")
        APP_NAME=$(echo "$FULL_NAME" | sed -E 's/^user-(.*)-deployed$/\1/')
        echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV

    - name: Update placeholders in manifests/application.yaml
      run: |
          sed -i -e "s|{{APP_NAME}}|${{ env.APP_NAME }}|" \
                 -e "s|{{REPO_URL}}|https://github.com/${{ github.repository }}|" \
                 -e "s|{{REPO_PATH}}|manifests|" \
                 -e "s|{{DEST_NAMESPACE}}|${{ env.APP_NAME }}|" \
                 manifests/application.yaml
    - name: Update placeholders in manifests/ingress.yaml
      run: |
          sed -i -e "s|{{APP_NAME}}|${{ env.APP_NAME }}|"  manifests/ingress.yaml
    - name: Commit and push updated manifest
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add manifests/application.yaml
        git add manifests/ingress.yaml
        git commit -m "Update application and ingress with deployment values"
        git push
    - name: Deploy ArgoCD Application
      run: kubectl apply -f manifests/application.yaml -n argocd

